import { pool } from "@/lib/db";

export type SubscriptionTier = "BRONZE" | "SILVER" | "GOLD";

export type SubscriptionFeatures = {
  aiPerformanceSummaries: boolean;
  autoGeneratedPapers: boolean;
  completeStudentReports: boolean;
  timeSpentPerQuestion: boolean;
  personalizedWeakAreaTests: boolean;
  brandedApp: boolean;
  customQuestions: boolean;
  parentWhatsAppReports: boolean;
};

export const SUBSCRIPTION_FEATURES: Record<SubscriptionTier, SubscriptionFeatures> = {
  BRONZE: {
    aiPerformanceSummaries: false,
    autoGeneratedPapers: false,
    completeStudentReports: false,
    timeSpentPerQuestion: false,
    personalizedWeakAreaTests: false,
    brandedApp: false,
    customQuestions: false,
    parentWhatsAppReports: false,
  },
  SILVER: {
    aiPerformanceSummaries: true,
    autoGeneratedPapers: true,
    completeStudentReports: true,
    timeSpentPerQuestion: true,
    personalizedWeakAreaTests: true,
    brandedApp: false,
    customQuestions: false,
    parentWhatsAppReports: false,
  },
  GOLD: {
    aiPerformanceSummaries: true,
    autoGeneratedPapers: true,
    completeStudentReports: true,
    timeSpentPerQuestion: true,
    personalizedWeakAreaTests: true,
    brandedApp: true,
    customQuestions: true,
    parentWhatsAppReports: true,
  },
};

export const SUBSCRIPTION_LIMITS: Record<SubscriptionTier, {
  selfTestsPerStudentPerMonth: number | null;
  teacherLogins: number | null;
}> = {
  BRONZE: { selfTestsPerStudentPerMonth: 10, teacherLogins: 3 },
  SILVER: { selfTestsPerStudentPerMonth: 30, teacherLogins: 8 },
  GOLD: { selfTestsPerStudentPerMonth: null, teacherLogins: null },
};

let schemaPromise: Promise<void> | null = null;

export function normalizeSubscriptionTier(value: unknown): SubscriptionTier {
  const normalized = String(value ?? "")
    .trim()
    .toUpperCase();

  if (normalized === "BRONZE") return "BRONZE";
  if (normalized === "SILVER") return "SILVER";
  return "GOLD";
}

export async function ensureSubscriptionSchema() {
  if (!schemaPromise) {
    schemaPromise = (async () => {
      await pool.query(`
        ALTER TABLE academies
        ADD COLUMN IF NOT EXISTS subscription_tier VARCHAR(20)
      `);

      // Existing academies keep their current full feature set. New tiers are
      // explicitly selected by the master admin and are then enforced centrally.
      await pool.query(`
        UPDATE academies
        SET subscription_tier = 'GOLD'
        WHERE subscription_tier IS NULL OR TRIM(subscription_tier) = ''
      `);

      await pool.query(`
        ALTER TABLE academies
        ALTER COLUMN subscription_tier SET DEFAULT 'GOLD'
      `);

      await pool.query(`
        CREATE INDEX IF NOT EXISTS idx_academies_subscription_tier
        ON academies(subscription_tier)
      `);
    })().catch((error) => {
      schemaPromise = null;
      throw error;
    });
  }

  return schemaPromise;
}

export async function getAcademySubscription(academyId: string) {
  await ensureSubscriptionSchema();

  const result = await pool.query(
    `
      SELECT subscription_tier, domain
      FROM academies
      WHERE id = $1
      LIMIT 1
    `,
    [academyId]
  );

  const domain = String(result.rows[0]?.domain || "").trim().toLowerCase();
  const tier = ["infinityclasses.net", "web.infinityclasses.net"].includes(domain)
    ? "GOLD"
    : normalizeSubscriptionTier(result.rows[0]?.subscription_tier);

  return {
    tier,
    features: SUBSCRIPTION_FEATURES[tier],
    limits: SUBSCRIPTION_LIMITS[tier],
  };
}

export async function academyHasFeature(
  academyId: string,
  feature: keyof SubscriptionFeatures
) {
  const subscription = await getAcademySubscription(academyId);
  return subscription.features[feature];
}

export async function requireAcademyFeature(
  academyId: string,
  feature: keyof SubscriptionFeatures
) {
  const subscription = await getAcademySubscription(academyId);

  if (!subscription.features[feature]) {
    return {
      allowed: false as const,
      subscription,
    };
  }

  return {
    allowed: true as const,
    subscription,
  };
}
/*
 * =========================================================
 * BACKWARD-COMPATIBILITY HELPERS
 * =========================================================
 *
 * Some newer API routes use these names:
 *   getAcademyTier
 *   hasTierFeature
 *   normalizeTier
 *   TierFeature
 *
 * Keep them as wrappers around the central subscription system
 * so all tier checks continue to use one source of truth.
 */

export type TierFeature =
  | keyof SubscriptionFeatures
  | "AI_PERFORMANCE_SUMMARIES"
  | "AUTO_GENERATED_PAPERS"
  | "COMPLETE_STUDENT_REPORTS"
  | "TIME_SPENT_PER_QUESTION"
  | "TIME_PER_QUESTION"
  | "PERSONALIZED_WEAK_AREA_TESTS"
  | "AI_WEAK_AREA_TESTS"
  | "BRANDED_APP"
  | "CUSTOM_QUESTIONS"
  | "PARENT_WHATSAPP_REPORTS"
  | "WHATSAPP_PARENT_REPORTS";

export const normalizeTier = normalizeSubscriptionTier;

function normalizeTierFeature(
  feature: TierFeature
): keyof SubscriptionFeatures | null {
  switch (feature) {
    case "aiPerformanceSummaries":
    case "AI_PERFORMANCE_SUMMARIES":
      return "aiPerformanceSummaries";

    case "autoGeneratedPapers":
    case "AUTO_GENERATED_PAPERS":
      return "autoGeneratedPapers";

    case "completeStudentReports":
    case "COMPLETE_STUDENT_REPORTS":
      return "completeStudentReports";

    case "timeSpentPerQuestion":
case "TIME_SPENT_PER_QUESTION":
case "TIME_PER_QUESTION":
  return "timeSpentPerQuestion";

  case "personalizedWeakAreaTests":
case "PERSONALIZED_WEAK_AREA_TESTS":
case "AI_WEAK_AREA_TESTS":
  return "personalizedWeakAreaTests";

    case "brandedApp":
    case "BRANDED_APP":
      return "brandedApp";

    case "customQuestions":
    case "CUSTOM_QUESTIONS":
      return "customQuestions";

    case "parentWhatsAppReports":
case "PARENT_WHATSAPP_REPORTS":
case "WHATSAPP_PARENT_REPORTS":
  return "parentWhatsAppReports";

    default:
      return null;
  }
}

/**
 * Return only the academy's current subscription tier.
 */
export async function getAcademyTier(
  academyId: string
): Promise<SubscriptionTier> {
  const subscription = await getAcademySubscription(academyId);
  return subscription.tier;
}

/**
 * Check whether a tier has a particular feature.
 *
 * Supports both:
 *   hasTierFeature("GOLD", "aiPerformanceSummaries")
 *   hasTierFeature("GOLD", "AI_PERFORMANCE_SUMMARIES")
 */
export function hasTierFeature(
  tier: SubscriptionTier | string,
  feature: TierFeature
): boolean {
  const normalizedTier = normalizeSubscriptionTier(tier);
  const normalizedFeature = normalizeTierFeature(feature);

  if (!normalizedFeature) {
    return false;
  }

  return SUBSCRIPTION_FEATURES[normalizedTier][normalizedFeature];
}
